services:
  actindomiddleware:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actindomiddleware
    ports:
      - "2233:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - actindo_data:/app/App_Data
      - ./.actindo-refresh-token:/app/.actindo-refresh-token
    networks:
      - monitoring_default
    restart: unless-stopped

networks:
  monitoring_default:
    external: true

volumes:
  actindo_data:
