services:
  actindomiddleware:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actindomiddleware
    ports:
      - "2233:8080"  # Äußerer Port 2233 -> Innerer Port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - monitoring_default
    restart: unless-stopped


networks:
  monitoring_default:
    external: true
